[tox]
envlist =
    py311-deps_min
    py311-deps_latest
    py312-deps_min
    py312-deps_latest

[testenv]
deps =
    deps_min: eclipse-zenoh==1.1.0
    deps_min: numpy==1.26.0
    deps_min: loguru==0.5.0
    deps_latest: eclipse-zenoh
    deps_latest: numpy
    deps_latest: loguru

commands = python tests/test_min_versions.py
